import { test, expect } from '@playwright/test';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { LoginPage } from '../../pages/login.page';
import { testUsers } from '../../utils/test-data';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function csvToInvoiceHtml(csv: string): string {
  const [headerLine, ...dataLines] = csv.trim().split(/\r?\n/);
  const headers = headerLine.split(',');
  const rows = dataLines.map((line) => line.split(','));

  return `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: Arial, sans-serif; color: #1f2937; padding: 32px; }
          h1 { color: #991b1b; margin-bottom: 8px; }
          p { margin-top: 0; color: #4b5563; }
          table { border-collapse: collapse; width: 100%; margin-top: 24px; }
          th, td { border: 1px solid #d1d5db; padding: 10px; text-align: left; }
          th { background: #f3f4f6; }
        </style>
      </head>
      <body>
        <h1>Invoice</h1>
        <p>Generated by Playwright checkout automation.</p>
        <table>
          <thead>
            <tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join('')}</tr>
          </thead>
          <tbody>
            ${rows
              .map(
                (row) =>
                  `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`
              )
              .join('')}
          </tbody>
        </table>
      </body>
    </html>
  `;
}

test.describe('Product Checkout', () => {
  test('@smoke should login and checkout any product', async ({ page }) => {
    const loginPage = new LoginPage(page);

    await loginPage.goto();
    await loginPage.login(testUsers.validUser.email, testUsers.validUser.password);
    await loginPage.expectLoginSuccess();

    const productCard = page.locator('.card-body').first();
    await expect(productCard).toBeVisible();

    const productName = (await productCard.locator('b').textContent())?.trim();
    expect(productName, 'Expected the first product card to have a product name').toBeTruthy();

    await productCard.getByRole('button', { name: /add to cart/i }).click();
    await expect(page.locator('#toast-container')).toContainText(/added to cart/i);

    await page.locator("[routerlink*='cart']").click();
    await expect(page.getByRole('listitem').filter({ hasText: productName as string })).toBeVisible();

    await page.getByRole('button', { name: /checkout/i }).click();
    await expect(page).toHaveURL(/.*\/#\/dashboard\/order/);

    await page.locator('[placeholder*="Country"]').pressSequentially('ind');
    await page.locator('.ta-results button').filter({ hasText: /^ India$/ }).click();

    await page.getByText('Place Order').click();
    await expect(page.locator('.hero-primary')).toContainText(/thankyou for the order/i);

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: /download/i }).click();
    const download = await downloadPromise;
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const downloadedPath = await download.path();

    expect(await download.failure()).toBeNull();
    expect(downloadedPath, 'Expected invoice download to be available locally').toBeTruthy();

    const invoiceCsv = await readFile(downloadedPath as string, 'utf-8');
    const invoicePath = path.resolve('invoice', `invoice-${timestamp}.pdf`);
    const pdfPage = await page.context().newPage();

    await mkdir(path.dirname(invoicePath), { recursive: true });
    await pdfPage.setContent(csvToInvoiceHtml(invoiceCsv));
    await pdfPage.pdf({ path: invoicePath, format: 'A4', printBackground: true });
    await pdfPage.close();
  });
});
